# Generated by Django 3.0.5 on 2020-04-17 21:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200417_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
