# Generated by Django 3.0.5 on 2020-04-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200417_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='accepted',
            new_name='published',
        ),
    ]
