# Generated by Django 3.0.5 on 2020-04-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200418_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
