# Generated by Django 3.0.5 on 2020-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='interesting', help_text='What do you think about it?'),
            preserve_default=False,
        ),
    ]
