# Generated by Django 3.0.5 on 2020-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200418_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='What do you think about it?', max_length=1024),
        ),
    ]
